# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Voices of Merced County
email: admin@joshua.bio
owner: Joshua Gonzales
author: Irene De La Cruz
subtitle: A show about the wonderful folks of Merced County
description: Voices of Merced County is a weekly podcast and radio show that airs every Saturday. Get to know the people of Merced County one conversation at a time.
baseurl: "/vomc"
url: "https://joshua.bio"
image: "https://s3-us-west-1.amazonaws.com/vomc-podcast/vomc.jpg"
twitter_username: jjfmg
github_username:  jjfmg

# Build settings
markdown: kramdown
